openapi: 3.0.2
info:
  title: API定義
  description: |
    情報実験のロビー用のサーバです
  version: 1.1.0
  contact:
    url: 'http://github.com/THEToilet'
servers:
  - url: 'http://localhost:8080'
tags:
  - name: auth
    description: 認証
  - name: user
    description: ユーザ関連APIs
  - name: image
    description: 画像関連API
  - name: category
    description: カテゴリ関連API
  - name: room
    description: 部屋関連API
paths:
  /login:
    post:
      tags:
        - auth
      summary: ユーザログインAPI
      description: |
        ログインを行います
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    type: string
                    description: トークン
        '400':
          description: Bad Request
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: ユーザId
                userPassword:
                  type: string
                  description: ユーザパスワード
      operationId: '5'
  /entry:
    post:
      tags:
        - auth
      summary: ユーザ登録API
      description: |
        ユーザ情報を登録します
      responses:
        '200':
          description: A successful response.
          content: {}
        '400':
          description: Bad Request
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                userName:
                  type: string
                userPassword:
                  type: string
      operationId: '3'
  /logout:
    get:
      tags:
        - auth
      summary: ユーザログアウトAPI
      description: |
        ログアウトを行います
      parameters:
        - name: session
          in: header
          description: 認証トークン
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response.
          content: {}
        '400':
          description: Bad Request
      x-codegen-request-body-name: body
      operationId: '6'
  /user/update:
    post:
      tags:
        - user
      summary: ユーザ情報更新API
      description: |
        ユーザ情報の更新をします。
        名前の更新を行います。
      parameters:
        - name: session
          in: header
          description: 認証トークン
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response.
          content: {}
        '400':
          description: Bad Request
      x-codegen-request-body-name: body
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: ユーザのId
                userName:
                  type: string
                  description: 変更した後のユーザ名
      operationId: '9'
  /image/list:
    get:
      tags:
        - image
      summary: カテゴリーに基づく画像一覧取得API
      description: 画像一覧を返します
      parameters:
        - name: session
          in: header
          description: 認証トークン
          required: true
          schema:
            type: string
        - schema:
            type: string
          in: query
          name: categoryId
          description: カテゴリー
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  images:
                    type: object
                    properties:
                      imageUrl:
                        type: string
                        description: url
                      fileName:
                        type: string
                        description: ファイル名
                      fileExtension:
                        type: string
                        description: ファイル拡張子
        '400':
          description: Bad Request
      operationId: '4'
  /category/list:
    get:
      tags:
        - category
      summary: カテゴリ一覧情報取得API
      description: カテゴリーの一覧情報を取得します。
      parameters:
        - name: session
          in: header
          description: 認証トークン
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    type: object
                    properties:
                      categoryId:
                        type: string
                        description: カテゴリーのId
                      categoryName:
                        type: string
                        description: カテゴリーの名前
        '400':
          description: Bad Request
      operationId: '1'
  '/category/{categoryId}/join':
    get:
      tags:
        - category
      summary: カテゴリーを指定して部屋に入るAPI
      description: カテゴリーを指定して部屋に入るAPI
      parameters:
        - name: session
          in: header
          description: 認証トークン
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roomId:
                    type: string
        '400':
          description: Bad Request
      operationId: '2'
    parameters:
      - schema:
          type: string
        name: categoryId
        in: path
        required: true
        description: カテゴリーId
  '/room/{roomId}/exit':
    get:
      tags:
        - room
      summary: 待機中の部屋を抜けるAPI
      description: 待機中の部屋を抜けるときに叩きます
      parameters:
        - name: session
          in: header
          description: 認証トークン
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      operationId: '7'
    parameters:
      - schema:
          type: string
        name: roomId
        in: path
        required: true
        description: ルームId
  '/room/{roomId}/wait':
    get:
      tags:
        - room
      summary: ルーム待機中API
      description: 部屋が完成するまで一秒間ごとにこのAPIを叩きます
      parameters:
        - name: session
          in: header
          description: 認証トークン
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  numberOfWaitUser:
                    type: integer
                  start:
                    type: boolean
        '400':
          description: Bad Request
      operationId: '8'
    parameters:
      - schema:
          type: string
        name: roomId
        in: path
        required: true
        description: ルームId
components:
  schemas: {}
  securitySchemes: {}
